export const experienceList = [
  {
    id: 1,
    title: 'Desenvolvedor Front-end Plêno',
    titleTranslated: 'Mid-Level Front-End Developer',
    company: 'Defensoria Pública do Estado do Pará',
    companyTranslated: 'Public Defender of the State of Pará',
    companyUrl: 'https://defensoria.pa.def.br/',
    date: '2024 - 2025',
  },
  {
    id: 2,
    title: 'Desenvolvedor Full Stack Jr',
    titleTranslated: 'Junior Front-End Developer',
    company: 'Frexco Tecnologia',
    companyTranslated: 'Frexco Technology',
    companyUrl: 'https://www.frexco.com.br',
    date: '2022 - 2023',
  },
  {
    id: 3,
    title: 'Desenvolvedor Full-stack Jr',
    titleTranslated: 'Junior Full stack developer',
    company: 'Cs - Consoft',
    companyTranslated: 'Cs - Consoft',
    companyUrl: 'http://cs-consoft.com.br',
    date: '2021 - 2022',
  },
  {
    id: 4,
    title: 'Desenvolvedor Full-stack Estagiário',
    titleTranslated: 'Intern Full stack developer',
    company: 'SEGUP - Secretaria de Segurança Pública do Pará',
    companyTranslated: 'SEGUP - Secretary of Public Security of Pará',
    companyUrl: 'https://www.segup.pa.gov.br',
    date: '2021 - 2021',
  },
  {
    id: 5,
    title: 'Bacharelado em Ciência da Computação',
    titleTranslated: `Bachelor's Degree in Computer Science`,
    company: 'Cesupa - Centro Universitário do Estado do Pará',
    companyTranslated: 'Cesupa - University Center of the State of Pará',
    companyUrl: 'https://www.cesupa.br',
    date: '2019 - 2022',
  },
];
